Web/Areas/Admin/Controllers/OrderController.cs
using Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IOredrService _orderService;

        public OrderController(IOredrService orderService)
        {
            _orderService = orderService;
        }
        public IActionResult Index(int page=1,int pageSize=5)
        {
            var model = new OrderViewModel()
            {
                Orders = _orderService.GetOrders(page,pageSize)
            };

            return View(model);
        }
    }
}

Web/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductController(ILogger<ProductController> ilogger, IProductService productService, ICategoryService categoryService)
        {
            _logger = ilogger;
            _productService = productService;
            _categoryService = categoryService;
        }
        [Authorize(Permissions.Products.Defualt)]
        public IActionResult Index(int? categoryId, int page = 1, int PageSize = 5)
        {
            var model = new ProductViewModel()
            {
                Products = _productService.GetProducts(categoryId, page, PageSize),
                CategoryId = categoryId,

            };
            FillUp(model);
            return View(model);
        }
        [Authorize(Permissions.Products.Add)]
        public IActionResult Create()
        {
            var model = new ProductViewModel()
            {
                Product = new ProductInputDto()
            };
            FillUp(model);
            return View(model);
        }
        [HttpPost]
        [Authorize(Permissions.Products.Add)]
        public IActionResult Create(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Product.Image != null)
                    {
                        var fileName = $"{Guid.NewGuid()}-{model.Product.Image.FileName}";
                        var filepath =
                            new PhysicalFileProvider(
                                    System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Products"))
                                .Root + $@"\{fileName}";

                        using FileStream fs = System.IO.File.Create(filepath);
                        model.Product.Image.CopyTo(fs);
                        fs.Flush();
                        model.Product.ImagePath = fileName;
                    }
                    _productService.AddProduct(model.Product);
                    model.Message = "Added Successfully";
                    model.Success = true;
                }

                catch (Exception ex)
                {
                    _logger.LogError(ex.Message, ex);
                    model.Message = "GenericError";
                    model.Success = false;
                }
            }
            else
            {
                model.Message = "InvalidInputs";
                model.Success = false;
            }


            FillUp(model);
            return View(model);
        }
        [Authorize(Permissions.Products.Edit)]
        public IActionResult Edit(Guid id)
        {
            var model = new ProductViewModel()
            {
                Product = _productService.GetProduct(id)
            };
            FillUp(model);
            return View(model);
        }

        [HttpPost]
        [Authorize(Permissions.Products.Edit)]
        public IActionResult Edit(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var product = _productService.GetProduct(model.Product.Id);
                    if (model.Product.Image != null)
                    {
                        var fileName = $"{Guid.NewGuid()}-{model.Product.Image.FileName}";
                        var filepath =
                            new PhysicalFileProvider(
                                    System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Products"))
                                .Root + $@"\{fileName}";

                        using FileStream fs = System.IO.File.Create(filepath);
                        model.Product.Image.CopyTo(fs);
                        fs.Flush();
                        model.Product.ImagePath = fileName;
                        if (product != null && !string.IsNullOrWhiteSpace(product.ImagePath))
                        {
                            deleteImage(product.ImagePath);
                        }
                    }
                    _productService.UpdateProduct(model.Product);
                    model.Message = "Updated Successfuly";
                    model.Success = true;
                }

                catch (Exception ex)
                {
                    model.Message = "GenericError";
                    model.Success = false;
                }
            }
            else
            {
                model.Message = "InvalidInputs";
                model.Success = false;
            }
            FillUp(model);
            return View(model);
        }
        [HttpPost]
        [Authorize(Permissions.Products.Delete)]
        public IActionResult Delete(Guid id)
        {
            try
            {
                _productService.Delete(id);
                return Json(new
                {
                    Message = "Item Deleted",
                    Success = true
                });
            }

            catch (Exception ex)
            {

                return Json(new
                {
                    Message = "GenericError",
                    Success = false
                });
            }
        }
        private void FillUp(ProductViewModel model)
        {
            model.CategoriesList = _categoryService.GetCategories()
                    .Select(c => new SelectListItem()
                    {
                        Text = c.Name,
                        Value = c.Id.ToString()
                    }).ToList();
        }
        private void deleteImage(string image)
        {

            var path = new PhysicalFileProvider(System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Products")).Root + $@"\{image}";

            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
        }
    }
}

Web/Areas/Admin/Controllers/RolesController.cs
using Core.Common.Exceptions;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RolesController : Controller
    {
        private readonly ILogger<RolesController> _logger;
        private readonly ISecurityService _securityService;
        public RolesController(ILogger<RolesController> logger, UserManager<User> userManager,
            RoleManager<Role> roleManager,
         ISecurityService securityService)
        {
            _securityService = securityService;
            _logger = logger;
        }
        public IActionResult Index(int page = 1, int pageSize = 25)
        {
            var model = new RoleViewModel
            {
                Roles = _securityService.GetRoles(page, pageSize)
            };
            return View(model);
        }

        public IActionResult Add()
        {
            var model = new RoleViewModel()
            {
                RoleInput = new RoleInputDto()
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Add(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _securityService.AddRole(model.RoleInput);
                    model.Success = true;
                    model.Message = "Added Successfuly";

                }
                catch (BusinessValidationException ex)
                {
                    _logger.LogInformation(ex, ex.Message);
                    model.Success = false;
                    model.Message = ex.Message;

                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                    model.Success = false;
                    model.Message = "Faild";


                }
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = new RoleViewModel()
            {
                RoleInput = await _securityService.GetRole(id)
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _securityService.EditRole(model.RoleInput);
                    model.Success = true;
                    model.Message = "Added Successfuly";

                }
                catch (BusinessValidationException ex)
                {
                    _logger.LogInformation(ex, ex.Message);
                    model.Success = false;
                    model.Message = "Faild";

                }

                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                    model.Success = false;
                    model.Message = "Error";


                }
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _securityService.RemoveRole(id);
                return Json(new
                {
                    Sucess = true,
                    Message = "Deltetdd Successsfuly"
                });
            }
            catch (BusinessValidationException ex)
            {
                return Json(new
                {

                    Success = false,
                    Message = "Faild"
                });

            }
            catch (Exception)
            {

                return Json(new
                {
                    Sucess = false,
                    Message = "Error"
                });
            }
        }




    }
}

Web/Areas/Admin/Controllers/UserController.cs
using Core.Common.Exceptions;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly ISecurityService _securityService;

        public UserController(ILogger<UserController> logger, UserManager<User> userManager,
           ISecurityService securityService)
        {
            _logger = logger;
            _securityService = securityService;
        }
        [Authorize(Permissions.Users.Defualt)]
        public IActionResult Index(int page = 1, int pageSize = 25)
        {
            var model = new UserViewModel
            {
                Users = _securityService.GetUsers(page, pageSize)
            };
            return View(model);
        }
        public IActionResult Add()
        {
            var model = new UserViewModel()
            {
                User = new UserInputDto()
                {
                    UserRoles = new List<UserRoleDto>()
                }
            };
            FillUp(model);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Add(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.User.UserRoles = model.User.UserRoles.Where(r => r != null).ToList();
                 await   _securityService.AddUser(model.User);
                    model.Success = true;
                    model.Message = "Added Successfuly";

                }
                catch (BusinessValidationException ex)
                {
                    _logger.LogInformation(ex, ex.Message);
                    model.Success = false;
                    model.Message = "Faild";

                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                    model.Success = false;
                    model.Message = "Faild";

                }
            }
            FillUp(model);
            return View(model);
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = new UserViewModel()
            {
                User = await _securityService.GetUser(id)
            };
            model.User.Password = "**";
            model.User.PasswordConfirm = "**";
            FillUp(model);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.User.UserRoles = model.User.UserRoles.Where(r => r != null).ToList();
                    await _securityService.EditUser(model.User);
                    model.Success = true;
                    model.Message = "Added Successfuly";

                }
                catch (BusinessValidationException ex)
                {
                    _logger.LogInformation(ex, ex.Message);
                    model.Success = false;
                    model.Message = "Faild";

                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                    model.Success = false;
                    model.Message = "Faild";
                }
            }
            model.User = await _securityService.GetUser(model.User.Id);
            FillUp(model);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {

            try
            {

                await _securityService.RemoveUser(id);
                return Json(new
                {
                    Sucess = true,
                    Message = "Deltetdd Successsfuly"
                });

            }
            catch (Exception)
            {
                return Json(new
                {
                    Sucess = false,
                    Message = "Error"
                });

            }
        }


        private void FillUp(UserViewModel model)
        {
            model.Roles = _securityService.GetRoles(1, int.MaxValue);
        }
    }
}

Web/Views/Shared/AdminLTE/_Footer.cshtml
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2023 <a href="#">Mahmoud Hassan</a>.</strong> All rights reserved.
  </footer>
</div>

Web/Views/Shared/AdminLTE/_LayoutNew.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <script src="~/plugins/jquery/jquery.min.js"></script>
  


    <title>Electronics Shop</title>
    <partial name="AdminLTE/_Styles" />
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <partial name="AdminLTE/_TopNavigation" />
        <partial name="AdminLTE/_MainNavigation" />
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-12">
                        <div class="col-sm-6">
                               @RenderSection("PageTitile",false)
                
                        </div>
                         <div class="col-sm-6">
                           
                    @RenderSection("PageMenue", false)
                        </div>
                    
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                   
                    @RenderBody()
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>

           <!--begin::Modal-->
    <div class="modal fade" id="popupForm" @*tabindex="-1"*@ role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="formTitle"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="form" method="post" class="popup">
                    <input hidden id="url"/>
                    <div class="modal-body" id="popupFormBody" style="margin: 0;">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="saveBtn" type="submit" class="btn btn-danger">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="popupInfo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="infoTitle"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body row" id="popupInfoBody" style="margin: 0;">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!--end::Modal-->
        <partial name="AdminLTE/_Footer" />
    </div>
    <partial name="AdminLTE/_Scripts" />
      <script src="~/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/plugins/jquery-validation/additional-methods.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
  
    <!-- end::Body -->
    <script src="~/assets/js/init.js"></script> 
</body>

</html>

Web/Views/Shared/AdminLTE/_MainNavigation.cshtml
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-action="Index" asp-controller="Home" asp-area="" class="brand-link">
      <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Electronics Shop</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="~/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">@User.Identity.Name</a>
        </div>
      </div>

 

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

               <li id="products"  class="nav-item">
            <a  href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Products
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li id="productsList" class="nav-item">
                <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Products List</p>
                </a>
              </li>
            </ul>
          </li>

               <li id="categories"  class="nav-item">
            <a  href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Categories
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li id="categoriesList" class="nav-item">
                <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Categories List</p>
                </a>
              </li>
            </ul>
          </li>
          
               <li id="orders"  class="nav-item">
            <a  href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Orders
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li id="ordersList" class="nav-item">
                <a asp-area="Admin" asp-controller="Order" asp-action="Index" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Orders List</p>
                </a>
              </li>
            </ul>
          </li>
           <li id="users"  class="nav-item">
            <a  href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Users
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li id="usersList" class="nav-item">
                <a asp-area="Admin" asp-controller="User" asp-action="Index" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>UsersList</p>
                </a>
              </li>
            </ul>
          </li>
           <li id="roles" class="nav-item">
            <a  href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Roles
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li id="rolesList" class="nav-item">
                <a  asp-area="Admin" asp-controller="Roles" asp-action="Index" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>RolesList</p>
                </a>
              </li>
        
            
            </ul>
          </li>
      
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

Web/Views/Shared/AdminLTE/_Scripts.cshtml
@*
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="~/plugins/select2/js/select2.full.js"></script>

*@
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="~/js/adminlte.min.js"></script>





 <script type="text/javascript">
      
        </script>

Web/Views/Shared/AdminLTE/_Styles.cshtml
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
 @* <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <link rel="stylesheet" href="~/plugins/select2/css/select2.min.css">*@
  <link rel="stylesheet" href="~/assets/css/bootstrap.css.map">
<link rel="stylesheet" href="~/css/adminlte.min.css">
<link rel="stylesheet" href="~/css/PagedList.css">


<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

Web/Views/Shared/AdminLTE/_TopNavigation.cshtml
@inject IHttpContextAccessor _httpContextAccessor
@{
    var id = _httpContextAccessor.HttpContext?.User?.FindFirst("Id");
}
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
   
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
        @if(id != null)
        { <li class="nav-item">
        <a class="nav-link" asp-action="LogOff" asp-controller="Account" asp-area="">
         <i class="fas fa-power-off"></i>
        </a>
      </li>
            
        }
       
    </ul>
  </nav>
  <!-- /.navbar -->